### ISSUE TITLE
Filter Block Doesn't Work As Documented

### ISSUE THREAD

**Issue by Taur1ne** [rackn/terraform-provider-drp#52]
Hello,

I am trying to filter based on name and the DRP provider is erroring out. 

DRP provider is v1.1.1
DigitlalRebar is v3.8.2

```
$ terraform -v
Terraform v0.11.7
+ provider.drp (unversioned)
$ terraform apply
Error: drp_machine.test1: filters.0: invalid or unknown key: value
```

Code:
```
$ cat test1.tf
resource "drp_machine" "test1" {
  count = 1
  Workflow = "Install16.04"
  Description = "Ubuntu 16.04 Terraform installation"
  Name        = "test1"
  add_profiles = ["root-access-password"]
  filters = [{
    name = "Name"
    value = "test1"
  }]
  timeouts {
    create = "2h"
  }
}
```

The name and value filters are displayed in your documentation here: http://provision.readthedocs.io/en/tip/doc/integrations/terraform.html#picking-machines-with-filter

If I remove the `value` filter, terraform apply will run, then crash and burn due to an unexpected EOF error
. 
Any ideas? Let me know if you need any additional information. 

Thanks,
Carroll

**Comment by zehicle** [comment]
It appears that the filter should read jsonvalue instead of value.  I'll update the documentation.

https://github.com/rackn/terraform-provider-drp/blob/1a583f626ec55b2658f530e66e4c804597aa7f81/drp/resource_drp_machine.go#L102

**Comment by zehicle** [comment]
I cannot comment about the EOF error - do you have any log information from Terraform or Rebar?  That may be another issue

**Comment by Taur1ne** [comment]
To be clear, using the jsonvalue filter, it still bombs out with an EOF. 

```bash
resource "drp_machine" "test1" {
  count = 1
  Workflow = "Install16.04"
  Description = "Ubuntu 16.04 test1 Terraform installation"
  Name        = "test1"
  add_profiles = ["root-access-password"]
  filters = [{
    name = "Name"
    jsonvalue = "test1"
  }]
  timeouts {
    create = "2h"
  }
}
```

**Comment by ravolt** [comment]
On quick review, it looks like it's trying to call power cycle but the impi is missing. 
I think there is a way to bypass that.  I'llLook. 


Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone
-------- Original message --------From: Taur1ne <notifications@github.com> Date: 7/10/18  1:27 PM  (GMT-05:00) To: rackn/terraform-provider-drp <terraform-provider-drp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [rackn/terraform-provider-drp] Filter Block Doesn't Work As Documented (#52) 
Hello Zehicle,
Sorry for the delay. Attached is a redacted (changed hostnames, paths, and IP addresses) log of the terraform crash using the jsonvalue  filter.
Let me know if you need any additional information.
Regards,

Carroll
redacted.log

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rackn/terraform-provider-drp","title":"rackn/terraform-provider-drp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rackn/terraform-provider-drp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Taur1ne in #52: Hello Zehicle,\r\n\r\nSorry for the delay. Attached is a redacted (changed hostnames, paths, and IP addresses) log of the terraform crash using the jsonvalue  filter.\r\n\r\nLet me know if you need any additional information.\r\n\r\nRegards,\r\nCarroll\r\n\r\n[redacted.log](https://github.com/rackn/terraform-provider-drp/files/2181450/redacted.log)"}],"action":{"name":"View Issue","url":"https://github.com/rackn/terraform-provider-drp/issues/52#issuecomment-403902943"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rackn/terraform-provider-drp/issues/52#issuecomment-403902943",
"url": "https://github.com/rackn/terraform-provider-drp/issues/52#issuecomment-403902943",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rackn/terraform-provider-drp] Filter Block Doesn't Work As Documented (#52)",
"sections": [
{
"text": "",
"activityTitle": "**Taur1ne**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Taur1ne",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rackn/terraform-provider-drp\",\n\"issueId\": 52,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"rackn/terraform-provider-drp\",\n\"issueId\": 52\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rackn/terraform-provider-drp/issues/52#issuecomment-403902943"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352613632\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Taur1ne** [comment]
The 'Packet IPMI' plugin is installed under 'Synchronize & Upload -> Plugin Providers', but we don't have it set under the 'System -> Plugins' tab. 

![image](https://user-images.githubusercontent.com/10520528/42904427-0fd7743c-8aa3-11e8-8e79-cd2bc582aa29.png)


The power cycle may have been called in the earlier logs due to 2 resources existing and one of them getting deleted from the terraform apply. I've deleted the two and started over from a fresh state with a single resource. The error is still occurring with the 'unexpected EOF' and Terraform bombing out. Attached is another [redacted.log](https://github.com/rackn/terraform-provider-drp/files/2207163/redacted.log)

Regards,
Carroll

**Comment by zehicle** [comment]
@Taur1ne you may need to login to get access to the Packet IPMI.  It should be available on those lists without a login.

ALSO - I've fixed the jsonvalue filter issue.   See #53
